// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "AdminMachine.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::SF::TRADE::THRIFT;

class AdminMachineHandler : virtual public AdminMachineIf {
 public:
  AdminMachineHandler() {
    // Your initialization goes here
  }

  void run(const TMSpec& tm) {
    // Your implementation goes here
    printf("run\n");
  }

  void kill(const TMSpec& tm) {
    // Your implementation goes here
    printf("kill\n");
  }

  void killall() {
    // Your implementation goes here
    printf("killall\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<AdminMachineHandler> handler(new AdminMachineHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new AdminMachineProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

