/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef trade_CONSTANTS_H
#define trade_CONSTANTS_H

#include "trade_types.h"

namespace SF { namespace TRADE { namespace THRIFT {

class tradeConstants {
 public:
  tradeConstants();

  std::string USER_TYPE_TALLENT;
  std::string USER_SKILLS;
  std::string USER_LINKS;
  int32_t LotsMultiplier;
  int32_t PriceMultiplier;
  int32_t MoneyMultiplier;
};

extern const tradeConstants g_trade_constants;

}}} // namespace

#endif
