/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "trade_constants.h"

namespace SF { namespace TRADE { namespace THRIFT {

const tradeConstants g_trade_constants;

tradeConstants::tradeConstants() {
  USER_TYPE_TALLENT = "TallentUserType";

  USER_SKILLS = "skills";

  USER_LINKS = "links";

  LotsMultiplier = 1000000;

  PriceMultiplier = 1000000;

  MoneyMultiplier = 100;

}

}}} // namespace

